### ISSUE TITLE
Implement consumer logic in the Simulator

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#121]
As a block node developer
I want to be able to test streaming data to a consumer
So we need to add consumer side setup on the simulator side to test out this capability.

---
### Additional Information

Currently the simulator does not have any working implementation for consuming data. There is already separtion in the code, therefore It would be easy to add this in the `consumerModeHandler`.

**Comment by a-saksena** [comment]
Needs a downstream dependent ticket in Mirror Node.

**Comment by Nana-EC** [comment]
@AlfredoG87 and @georgi-l95 we should pull this out of the current EPIC as it's not a Phase 1 goal.
Unclear if it need to be under a new EPIC or is fine as specified

**Comment by AlfredoG87** [comment]
I wonder why this is not part of Phase1, we should make it part, this is part of the MVP functionality of `Streaming from CN --> BN --> Consumers` first phase right?
