### ISSUE TITLE
EPIC: Essential Block Storage and Retrieval Architecture

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#122]
## Epic Goal
Design Architecture for essential block storage and retrieval support to enable the Phase 1 block node features (pre-release).

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/124
- [ ] https://github.com/hashgraph/hedera-block-node/issues/125
```

**Comment by a-saksena** [comment]
Let's carve out a separate epic for implementation (ph-2). Make this a design epic (ph-1).

**Comment by mattp-swirldslabs** [comment]
Was closed with the discussion about `trie` structure
