### ISSUE TITLE
EPIC: Performance Validation

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#160]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/161
```

**Comment by mattp-swirldslabs** [comment]
We've seen sufficient performance improvements with the additions of:
* PBJ types
* Selective PBJ parsing
* Helidon PBJ Plugin settings tuning
* Refactoring to bundle blockitems in batches of 1000
* Block-as-file I/O improvements

We're currently ingesting 60x the required number of real blocks per hour. We can open a new performance ticket if needed later.
