### ISSUE TITLE
refactor: adjust configuration management and smoke test setup to support production config by default

### ISSUE THREAD

**Issue by mattp-swirldslabs** [hashgraph/hedera-block-node#185]
As a Block Node administrator
I want production configuration by default
so that I can minimize dealing with app.properties changes

* Currently, `smoke_test.yaml` runs the smoke tests using `gradle run` to verify with `smoke_test.sh`
* It's more difficult to override the default configuration because this does not use a test app.properties file when it starts the Block Node
* Record files like: `MediatorConfig.java` and `NotifierConfig.java` currently must be defaulted to non-production values (e.g. 1024 for the ring buffer rather than a more realistic prod value like 67108864) so that the smoke test does not throw an OutOfMemory error.
* As a result, the production `app.properties` file must contain the prod values instead to override the defaults when running in a container.

Perhaps we should change the CI tests to:
1) Run the smoke tests via docker rather than gradle. Gradle is strictly used for build and development.
2) Set the defaults in the config record files like `MediatorConfig.java` and `NotifierConfig.java` to the production defaults
3) Remove the override values in `app.properties` to minimize the configuration burden.
4) Leverage the test `app.properties` inside the container noted in #1 to override the production defaults with test config.

**Comment by a-saksena** [comment]
@georgi-l95 , @AlfredoG87 -- Can you check if this is a good onboarding story for Atanas?

**Comment by AlfredoG87** [comment]
Yes I think is a good story for Atanas
