### ISSUE TITLE
EPIC: Implement Block verification prior to persistence

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-block-node#193]
### Problem

The BN must only store verified blocks.

### Solution

Add new logic to verify the block based on the block proof

----
Estimation considerations
1) Construct Proof Merkle Tree of hashes (this is not the State Tree)
2) Verify the proof/sign at the end using TSS library
3) Verify agg sign. (block poof in the incoming block) with a given a Public Key (Long term ledger Id) -- This can be achieved when some parts of ""TSS Library"" are available.

**Comment by Nana-EC** [comment]
Closing as a dupe of #89 and moved estimate notes there.

**Comment by AlfredoG87** [comment]
@berryware 
I believe issues: 
https://github.com/hiero-ledger/hiero-block-node/issues/2321
https://github.com/hiero-ledger/hiero-block-node/issues/2325

have already been addressed right?

**Comment by berryware** [comment]
That is correct
