### ISSUE TITLE
Estimate size of block stream blocks at 10K TPS at a mainnet style load

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#219]
Tech Note:
1. Got below info from https://github.com/hashgraph/hedera-block-node/issues/124#issuecomment-2383964185 

> @AlfredoG87 Here you are: https://perf.analytics.eng.hashgraph.io/ephemeral/data_block-streams_block-0.0.3_of_1Maccs.tgz
> In BOTH mode, generated 1.6Gb of blk.gz files, but running NFT transfer test

**Comment by Nana-EC** [comment]
@AlfredoG87 have we recorded this?
I think the initial estimation did not have realistic accounts with multiple keys etc.
If we have the numbers let's note them here and confirm with @jasperpotts and get this closed.
If not let's update this with the next steps of the investigation

**Comment by AlfredoG87** [comment]
Yes the original recording does not have keys and its only crypto transfer as you noted @Nana-EC, however is my understanding that @jasperpotts  has a new recording that simulates this much better.

**Comment by jsync-swirlds** [comment]
Block Stream data size (predicted).
The upper limit size, from Perf test, extrapolated to 6 months is 18.5 TB.
> This is calculated from actual perf test results, multiplied by the ratio of blocks in the test to blocks in _approximately_ half a year. The actual ratio used is 5015.

From this we have a "reasonable" range of 18-36T/year at near maximum TPS (range accounts for variability between real loads and perf-based estimates).

The "current" volume would, then, be less than 2-6T/year (based on real mainnet TPS compared to perf net TPS).
For future prediction scenarios below we will start with a 6T/year baseline.

Predictive growth scenarios:
Scenario 1 (Baseline) - Current transaction mix, 10% CAGR, no major new transaction types
6, 6.6, 7.2, 7.9, 8.8, 9.6, 11, 12, 13, 14, 16
112T total over 10 years.

Scenario 2 (HCS Inscriptions) - Strong shift toward a more stream-heavy transaction mix, 15% CAGR, no major new transaction types
9, 10, 12, 14, 16, 18, 21, 24, 27, 32, 36
219T total over 10 years.

Scenario 3 (Single shard limit) - No shift in transaction mix, 15% CAGR, 10K TPS from 2025-01-01, improved efficiency enables 15% annual TPS increases.
36, 41, 47, 54, 62, 72, 83, 95, 110, 126, 145
871T total over 10 years.

Scenario 4 (Hyper-Growth) - Modest shift to more stream-heavy transaction mix, 50% CAGR, some new transaction types, sharding enables 100K TPS
11, 16, 24, 37, 56, 83, 125, 188, 282, 423, 634
1879T total over 10 years.
