### ISSUE TITLE
Test, Fix and Follow-up on "Automated release process" attempt to release `0.1.0-rc1` and `0.1.0-rc2` versions.

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-block-node#229]
Recently the `release-automation.yaml` was merged into `main` to start automate the release process, however as expected, after merging, is necessary to do some adjustments, fixes and configurations to the repo to be able to iron-out the WF. This is expected since this is a fairly complex workflow with variables that are hard (close to impossible) to replicate locally. 

This tasks is a place-holder for the testing phase.

So far this has come up:
- [x] Change `secrets.HEDERA_BOT_TOKEN` for `secrets.GITHUB_TOKEN` at the checkout step.
- [x] Requested RE team to add the following secrets to the repo: `secrets.GPG_PRIVATE_KEY` and `secrets.GPG_PASSPHRASE`

The conclusion of this ticket is to iron-out the process and verify is working by sucessfully releasing `0.1.0` starting with  attempt to release `0.1.0-rc1` and `0.1.0-rc2` versions.

**Comment by AlfredoG87** [comment]
@rbarkerSL 
https://swirldslabs-help.freshdesk.com/support/tickets/5749

**Comment by rbarkerSL** [comment]
PR #236 will complete this ticket. @AlfredoG87
