### ISSUE TITLE
Fetch a specific block (by block #)

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#25]
AS A consumer app
I WANT TO fetch a specific block (by block #)
SO THAT I can retrieve specific data without the need to consume the whole stream. 

Tech Note:
1. Start with gRPC API. We could auto-map gRPC to REST later.
2. Single/Uni Get (not streaming)

**Comment by Nana-EC** [comment]
Looks like controller and service level foundation was added.
Need to confirm additional requirements on the endpoint to confirm the Epic completion
