### ISSUE TITLE
chore: Add all newer configuration items to Environment Variable mapping.

### ISSUE THREAD

**Issue by ata-nas** [hashgraph/hedera-block-node#285]
## What happened
Currently, there is some missing support for some configurable values via environment variables.

## What should to happen
In order to support environment variables for configuration classes, we need to map the conventional screaming snake case for environment variables (since still by default we are not able to get another case at runtime) to a convention the config api understands(e.g. `MEDIATOR_RING_BUFFER_SIZE` to `mediator.ringBufferSize`). This is done by updating the `com.hedera.block.server.config.ServerMappedConfigSourceInitializer#MAPPINGS` and we also need to update the respective awareness test `com.hedera.block.server.config.ServerMappedConfigSourceInitializerTest#SUPPORTED_MAPPINGS`. Also, alongside that, we should update the `README.md` to let the users know what are the correct screaming snake case keys for the configs.

## Tasklist
- [ ] Update all the other needed configurations that need to be supported to be set via environment variables in `:server`
- [ ] Update all the other needed configurations that need to be supported to be set via environment variables in `:simulator`

Missing configuration that should be added:
- From `server`:
   - producer.type → PRODUCER_TYPE (default: "PRODUCTION")
   - mediator.type → MEDIATOR_TYPE (default: "PRODUCTION")
- From `simulator`:
   - From GrpcConfig.java:
      - grpc.serverAddress (default: "localhost")
      - grpc.port (default: 8080)
   - From BlockStreamConfig.java:
      - blockStream.simulatorMode (default: "PUBLISHER")
      - blockStream.delayBetweenBlockItems (default: 1_500_000)
      - blockStream.maxBlockItemsToStream (default: 100_000)
      - blockStream.streamingMode (default: "MILLIS_PER_BLOCK")
      - blockStream.millisecondsPerBlock (default: 1000)
      - blockStream.blockItemsBatchSize (default: 1000)
   - From BlockGeneratorConfig.java:
      - generator.generationMode (default: "DIR")
      - generator.folderRootPath (default: "")
      - generator.managerImplementation (default: "BlockAsFileBlockStreamManager")
      - generator.paddedLength (default: 36)
      - generator.fileExtension (default: ".blk.gz")
      - generator.startBlockNumber (default: 1)
      - generator.endBlockNumber (default: -1)
## Version

0.2.0-SNAPSHOT

**Comment by AlfredoG87** [comment]
This is already merged, closing it.

**Comment by ata-nas** [comment]
@AlfredoG87 no, this should not be closed as it is not implemented/merged anywhere.

In the above description, it is given example of an already existing config in order to showcase what must be done to all the others that need to be supported via environment variables. This issue **IS NOT** about the example above, but for all the rest.
