### ISSUE TITLE
refactor: implement agreed upon changes based on discussion (#266)

### ISSUE THREAD

**Issue by ata-nas** [hashgraph/hedera-block-node#305]
## Description
Based on discussion #266, implement the changes agreed upon there as seen in the task list below.

## Tasklist
- create new class `MathUtilities`
- implement proposed change to create `isPowerOfTwo(int)` boolean check inside `MathUtilities`
- create new class `Preconditions`
- implement proposed change to create `requirePowerOfTwo(int)` strict precondition inside `Preconditions`
- implement proposed change to create `isBlank(String)` boolean check inside `StringUtilities`
- implement proposed change to move `StringUtilities#requireNotBlank(String)` to `Preconditions`

**Comment by AlfredoG87** [comment]
@ata-nas could you confirm if this is still pending or is already completed?

**Comment by ata-nas** [comment]
> @ata-nas could you confirm if this is still pending or is already completed?

@AlfredoG87 this is pending, I will be including it in one of my PRs soon
