### ISSUE TITLE
refactor: BlockAsDirReader and BlockAsDirWriter review and overhaul

### ISSUE THREAD

**Issue by ata-nas** [hashgraph/hedera-block-node#319]
## Story 
**AS A** BN Developer
**I WANT** a review and overhaul if needed of the `BlockAsDirReader` and `BlockAsDirWriter`
**SO THAT** concerns about current implementation are addressed and we are assured of their proper functioning.

## Tech Notes
Based on [this comment](https://github.com/hashgraph/hedera-block-node/pull/272#discussion_r1819555402) and the thread that proceeds it, there are a few concerns with the current implementation of the `BlockAsDirReader` and `BlockAsDirWriter`, mainly:
- currently both classes have a filed member `filePerms` which make no distinction between file and folder permissions
- it is important that files and folders have a different set of permissions, so such distinction should be made if necessarry
- it must be discussed if we should continue to use permissions like we do currently or another approach must be used, see [comment](https://github.com/hashgraph/hedera-block-node/pull/272#discussion_r1819555402)

**UPDATE:**
- these must now be integrated based on the changes in #309 and need to be matched under the abstractions that will now be adapted

**Comment by AlfredoG87** [comment]
I don't think is worth it to continue to work on these implementations since we should remove them once the BlockAsFile Writer and Reader are completed.

**Comment by ata-nas** [comment]
@AlfredoG87 during the implementation of #272 we reached the conclusion that we should revise these implementations here. It is true that if we shall delete them we should not work any longer over them, but my understanding is that the `BlockAsDirReader` and `BlockAsDirWriter` should NOT be deleted, @jsync-swirlds am I right about that?
