### ISSUE TITLE
docs: documentation reorganization and standardization

### ISSUE THREAD

**Issue by ata-nas** [hashgraph/hedera-block-node#325]
## Story
**AS A** User
**I WANT** to have a well structured, easy to find and browse documentation
**SO THAT** it will be easy to use and understand the applications

## Tech Notes
- have a well structured documentation layout
- documentation should support internal referencing
- documentation should have a hierarchical structure going from top to bottom
- easy to use
- well modularized per subproject and per topic

I would imagine the docs hierarchy as the one below (example given with only with `server` and `simulator` and just a couple of files to showcase the idea, for brevity):
```
REPO_ROOT/
├─ README.md
├─ server/
│  ├─ docs/
│  │  ├─ configuration.md
│  │  ├─ quickstart.md
│  │  ├─ ...
│  ├─ README.md
│  ├─ ...
├─ simulator/
│  ├─ docs/
│  │  ├─ configuration.md
│  │  ├─ quickstart.md
│  │  ├─ ...
│  ├─ README.md
│  ├─ ...
├─ ...
```
  
**ALTERNATIVE** (in case it makes more sense the README for a specific project to be inside the respective `/docs` folder, with exception to `REPO_ROOT`):
```
REPO_ROOT/
├─ README.md
├─ server/
│  ├─ docs/
│  │  ├─ configuration.md
│  │  ├─ quickstart.md
│  │  ├─ README.md
│  │  ├─ ...
│  ├─ ...
├─ simulator/
│  ├─ docs/
│  │  ├─ configuration.md
│  │  ├─ quickstart.md
│  │  ├─ README.md
│  │  ├─ ...
│  ├─ ...
├─ ...
```

 I would imagine the following things to be present in the files:
-  `REPO_ROOT/README.md`: this file in the root should have all the general info about the block node repo, nothing specific and technical for any project. It should be listing and linking to all the projects present in the repo, it should IMO act as a `Table of Contents` for the repo. Also all relevant links and references etc. should be present here;
- `REPO_ROOT/<any_project>/README.md` or `REPO_ROOT/<any_project>/docs/README.md` depending on option chosen above: this file should give us a general information for the specific project as a whole with a biref high level (or not so high level, this is debatable) overview of the specific project and it should be linking to the `/docs` folder that is on the same level as this specific project's readme. This readme should act as a `Table of Contents` for the specific project;
- `REPO_ROOT/<any_project>/docs`: here we have all the project specific documentation files, which IMO should be based on topic, the couple examples above show the `configuration.md` which would list all the possible configurations and what they stand for and have defaults and ranges and how to set them etc. etc. and also we show the `quickstart.md` which would give all information about ways we can get started with running the project locally;
- The documentation should be interactive and we should reference other parts of it as needed, for example, in the `quickstart.md` if we have a section on configuration, we should simply let the user know that they need to do their own configuration and we should link the `configuration.md`;
- Moreover, with this hierarchical approach going from top to bottom, previous higher level `README.md` files act as a `TOC` for the lower levels, this is a very natural and easy to understand and use way of having the documentation;
- all other project or repo relevant documentation, based on topic, should be in the respective `/docs` folder;

**Comment by jsync-swirlds** [comment]
I agree with the first proposal.
