### ISSUE TITLE
feat: Make server port configurable via a property in app.properties

### ISSUE THREAD

**Issue by mattp-swirldslabs** [hashgraph/hedera-block-node#345]
As an engineer running a Block Node
I want to be able to configure the `port` for the Block Node
So that I can run the server on a different port

## Tech Notes
* This property is currently exposed in `BlockNodeApp.start()`:

```
 // Build the web server
        // TODO: make port server a configurable value.
        final WebServer webServer = webServerBuilder
                .port(8080)
                .addProtocol(pbjConfig)
                .addRouting(pbjRouting)
                .addRouting(httpRouting)
                .build();
```
* We already have an established pattern for ingesting parameters found in app.properties in the Server.java class. This feature should follow the existing pattern.
* The property will need to be sanity checked as a positive integer with a min value of 1 and a reasonable max port value
* The current default 8080
* The property might be named `server.port`

**Comment by AlfredoG87** [comment]
according to IANA, the well-known ports are from `0` to `1023` so the min value should be `1024` and a max of `65,535` that is the maximun allowable port number due to the 16 bits restriction.
