### ISSUE TITLE
Adjust Helidon interfaces to translate to PBJ types

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#74]
AS A BN Dev
I WANT TO Translate ProtoC objects received from Helidon to PBJ objects.
SO THAT I can use PBJ objects in my business logic. 

Tech Note:
1. Serialize the ProtoC object to bytes and then deserialize to PBJ. 
2. @jsync-swirlds to give examples. 
3. PBJ is new for the team. 
4. Compilation needs to happen first (ref to other story)

**Comment by a-saksena** [comment]
Not necessary if Richard finishes his PBJ task first.

**Comment by jsync-swirlds** [comment]
Best example for conversion is the (now removed) [`protoToPbj` method](https://github.com/hashgraph/hedera-services/blob/698243f2cf676b2dbf0965c923131ec57117cabd/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java#L1224) Services used
